### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by Mibo5354** [perslev/CanvasSync#14]
```
Traceback (most recent call last):
  File "C:\Python37\Scripts\canvas.py", line 191, in <module>
    run_canvas_sync()
  File "C:\Python37\Scripts\canvas.py", line 134, in run_canvas_sync
    main_menu(settings)
  File "C:\Python37\Scripts\canvas.py", line 152, in main_menu
    main_menu(settings)
  File "C:\Python37\Scripts\canvas.py", line 152, in main_menu
    main_menu(settings)
  File "C:\Python37\Scripts\canvas.py", line 149, in main_menu
    main_menu(settings)
  File "C:\Python37\Scripts\canvas.py", line 156, in main_menu
    do_sync(settings, "")
  File "C:\Python37\Scripts\canvas.py", line 172, in do_sync
    synchronizer.sync()
  File "c:\python37\lib\site-packages\CanvasSync\CanvasEntities\synchronizer.py", line 123, in sync
    course.sync()
  File "c:\python37\lib\site-packages\CanvasSync\CanvasEntities\course.py", line 169, in sync
    child.sync()
  File "c:\python37\lib\site-packages\CanvasSync\CanvasEntities\module.py", line 175, in sync
    child.sync()
  File "c:\python37\lib\site-packages\CanvasSync\CanvasEntities\page.py", line 176, in sync
    was_downloaded = self.download()
  File "c:\python37\lib\site-packages\CanvasSync\CanvasEntities\page.py", line 140, in download
    if self.download_linked_files(body):
  File "c:\python37\lib\site-packages\CanvasSync\CanvasEntities\page.py", line 85, in download_linked_files
    canvas_file_urls = re.findall(r'data-api-endpoint=\"(.*?)\"', html_body)
  File "c:\python37\lib\re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

Sync does not finish due to this error. Most likely due to file being not available for download and no url is provided.

**Comment by perslev** [comment]
Hi, thank you for your feedback!

This issue should be resolved in the newest update (v0.2.4). If you are still experiencing problems, please let me know.
