### ISSUE TITLE
TypeError: write() argument must be str, not None

### ISSUE THREAD

**Issue by Mibo5354** [perslev/CanvasSync#16]
I'm not sure what the problem is, it's from the latest version.
```
Traceback (most recent call last):
  File "C:\Python37\Scripts\canvas-script.py", line 11, in <module>
    load_entry_point('CanvasSync==0.2.4', 'console_scripts', 'canvas')()
  File "c:\python37\lib\site-packages\bin\canvas.py", line 187, in entry
    run_canvas_sync()
  File "c:\python37\lib\site-packages\bin\canvas.py", line 132, in run_canvas_sync
    main_menu(settings)
  File "c:\python37\lib\site-packages\bin\canvas.py", line 150, in main_menu
    main_menu(settings)
  File "c:\python37\lib\site-packages\bin\canvas.py", line 147, in main_menu
    main_menu(settings)
  File "c:\python37\lib\site-packages\bin\canvas.py", line 154, in main_menu
    do_sync(settings, "")
  File "c:\python37\lib\site-packages\bin\canvas.py", line 170, in do_sync
    synchronizer.sync()
  File "c:\python37\lib\site-packages\CanvasSync\entities\synchronizer.py", line 126, in sync
    course.sync()
  File "c:\python37\lib\site-packages\CanvasSync\entities\course.py", line 163, in sync
    child.sync()
  File "c:\python37\lib\site-packages\CanvasSync\entities\module.py", line 169, in sync
    child.sync()
  File "c:\python37\lib\site-packages\CanvasSync\entities\page.py", line 172, in sync
    was_downloaded = self.download()
  File "c:\python37\lib\site-packages\CanvasSync\entities\page.py", line 144, in download
    out_file.write(body)
TypeError: write() argument must be str, not None
```

**Comment by perslev** [comment]
Hi, could you please check the following:

- That you no longer experience the crash in the latest version (commit 743545d)
- If the HTML page that caused CanvasSync to crash is 'empty' (the page exists but has no information) on the live version in Canvas

Thanks!

**Comment by perslev** [comment]
Hi, could you please check the following:

- That you no longer experience the crash in the latest version (commit 32d5e70)
- If the HTML page that caused CanvasSync to crash is 'empty' (the page exists but has no content) on the live version in Canvas

Thanks!
