### ISSUE TITLE
KeyError: 'course_code'

### ISSUE THREAD

**Issue by justinTM** [perslev/CanvasSync#19]
```
This is a first time setup.
You must specify at least the following settings in order to run CanvasSync:

[*] Sync path:             	/Users/<me>/Documents/canvas sync
[*] Canvas domain:         	https://<my school domain>.instructure.com
[*] Authentication token:  	<my token>
[*] Courses to be synced:  	Not set
Traceback (most recent call last):
  File "//anaconda3/bin/canvas", line 10, in <module>
    sys.exit(entry())
  File "//anaconda3/lib/python3.7/site-packages/bin/canvas.py", line 187, in entry
    run_canvas_sync()
  File "//anaconda3/lib/python3.7/site-packages/bin/canvas.py", line 132, in run_canvas_sync
    main_menu(settings)
  File "//anaconda3/lib/python3.7/site-packages/bin/canvas.py", line 146, in main_menu
    settings.set_settings()
  File "//anaconda3/lib/python3.7/site-packages/CanvasSync/settings/settings.py", line 152, in set_settings
    self._set_settings()
  File "//anaconda3/lib/python3.7/site-packages/CanvasSync/settings/settings.py", line 180, in _set_settings
    self.courses_to_sync = user_prompter.ask_for_courses(self, api=self.api)
  File "//anaconda3/lib/python3.7/site-packages/CanvasSync/settings/user_prompter.py", line 171, in ask_for_courses
    courses = [name[u"course_code"].split(";")[-1] for name in courses]
  File "//anaconda3/lib/python3.7/site-packages/CanvasSync/settings/user_prompter.py", line 171, in <listcomp>
    courses = [name[u"course_code"].split(";")[-1] for name in courses]
```

**Comment by justinTM** [comment]
copy-paste got chopped; KeyError is for 'course_id' (in the title too)

**Comment by sidpagariya** [comment]
Hey, this is happening because you have a course the college enrolled you in on Instructure but it wasn't activated yet!

**Comment by justinTM** [comment]
Thanks for the reply! I’ll try again with a new term in school :)

**Comment by hellodoiknowu** [comment]
I have the same problem! How could you fix it?

**Comment by hellodoiknowu** [comment]
Traceback (most recent call last):
  File "C:\Users\Susu\AppData\Local\Programs\Python\Python39\Scripts\canvas-script.py", line 33, in <module>
    sys.exit(load_entry_point('CanvasSync==0.2.4', 'console_scripts', 'canvas')())
  File "c:\users\susu\appdata\local\programs\python\python39\lib\site-packages\bin\canvas.py", line 187, in entry
    run_canvas_sync()
  File "c:\users\susu\appdata\local\programs\python\python39\lib\site-packages\bin\canvas.py", line 132, in run_canvas_sync
    main_menu(settings)
  File "c:\users\susu\appdata\local\programs\python\python39\lib\site-packages\bin\canvas.py", line 146, in main_menu
    settings.set_settings()
  File "c:\users\susu\appdata\local\programs\python\python39\lib\site-packages\CanvasSync\settings\settings.py", line 152, in set_settings
    self._set_settings()
  File "c:\users\susu\appdata\local\programs\python\python39\lib\site-packages\CanvasSync\settings\settings.py", line 180, in _set_settings
    self.courses_to_sync = user_prompter.ask_for_courses(self, api=self.api)
  File "c:\users\susu\appdata\local\programs\python\python39\lib\site-packages\CanvasSync\settings\user_prompter.py", line 171, in ask_for_courses
    courses = [name[u"course_code"].split(";")[-1] for name in courses]
  File "c:\users\susu\appdata\local\programs\python\python39\lib\site-packages\CanvasSync\settings\user_prompter.py", line 171, in <listcomp>
    courses = [name[u"course_code"].split(";")[-1] for name in courses]
KeyError: 'course_code'

**Comment by hellodoiknowu** [comment]
I can't fix it please help me!!!

**Comment by dsandall** [comment]
is there anything that can be done here, other than waiting for the class to be activated? There are classes on my account that will likely never be activated

**Comment by SungMatt** [comment]
Hello, resurrecting this old thread to provide a workaround:

I got this error as some of the courses I enrolled in aren't real courses, they just exist as placeholders, without a course_code.

The fix is quite simple, first, the settings helper agent cannot assume course_codes exist for all.  [#286c0ff](https://github.com/perslev/CanvasSync/commit/286c0ffeb2a273894790b4b47fdccf4deb8742cb) fixes this.
Next, the synchronizer cannot make that assumption either. The way I did it was to modify the synchronizer, such that if it attempted to create a Course object that does not have a course_code, it would return a KeyError, and the synchronizer will catch that KeyError and continue. The appropriate changes are to lines 97 and later:

```python3
# Create Course object
            try:
                course = Course(course_information,
                                parent=self,
                                settings=self.settings)
            except KeyError:
                continue
```

This should fix the downloading problem for those who have the KeyError.
